# run-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: poc-user-api
  labels:
    environment: production
    cloud.googleapis.com/location: europe-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: 1
        run.googleapis.com/cpu-throttling: 1000m
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        # Labels specific to this revision
        version: v1.0.2
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/your-project-id/your-repo/your-image:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "128Mi"
      serviceAccountName: your-service-account-email@your-project-id.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300 # Default is 300 (5 minutes)