name: Set Google Secret Manager Secrets
on: push

env:
  project_id: ${{ vars.GCP_PROJECT_ID }}
  project_number: ${{ vars.GCP_PROJECT_NUMBER }}

jobs:
  set-secrets:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.project_id }}
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.WIF_SA }}

      - name: Set secrets
        uses: thoughtgears/action-set-secretmanager-secret@main
        with:
          project_id: ${{ env.project_id }}
          secrets: MY_SECRET=project-id=${{ env.project_id }},project-number=${{ env.project_number }}