name: Init

on:
  workflow_call:
    outputs:
      service_name:
        description: "Service name"
        value: ${{ jobs.init.outputs.service_name }}
      repository_name:
        description: "Repository name"
        value: ${{ jobs.init.outputs.repository_name }}
      repository_owner:
        description: "Repository owner"
        value: ${{ jobs.init.outputs.repository_owner }}
      commit_sha:
        description: "Full commit SHA"
        value: ${{ jobs.init.outputs.full_sha }}
      commit_short_sha:
        description: "Short commit SHA"
        value: ${{ jobs.init.outputs.short_sha }}

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    outputs:
      service_name: ${{ steps.get-service.outputs.service_name }}
      repository_name: ${{ steps.get-repo-info.outputs.repository_name }}
      repository_owner: ${{ steps.get-repo-info.outputs.repository_owner }}
      full_sha: ${{ steps.get-git-sha.outputs.full_sha }}
      short_sha: ${{ steps.get-git-sha.outputs.short_sha }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Get Service Name
        id: get-service
        run: |
          SERVICE_NAME=$(jq -r '.name' package.json)
          echo "service_name=${SERVICE_NAME}" >> $GITHUB_OUTPUT

      - name: Get Repository Name and Owner
        id: get-repo-info
        run: |
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          REPOSITORY_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          echo "repository_name=${REPOSITORY_NAME}" >> $GITHUB_OUTPUT
          echo "repository_owner=${REPOSITORY_OWNER}" >> $GITHUB_OUTPUT

      - name: Get Git SHA
        id: get-git-sha
        run: |
          FULL_SHA="${{ github.sha }}"
          SHORT_SHA="${FULL_SHA:0:7}"
          echo "full_sha=${FULL_SHA}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT