name: Terraform Apply

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      gcp_project_number:
        required: true
        type: string
      terraform_state_bucket:
        required: true
        type: string
      wif_provider:
        required: true
        type: string
      wif_sa:
        required: true
        type: string
    outputs:
      apply_result:
        description: "Results from terraform apply in JSON format"
        value: ${{ jobs.apply.outputs.output_json }}


jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    outputs:
      apply_json: ${{ steps.parse_output.outputs.output_json }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          workload_identity_provider: ${{ inputs.wif_provider }}
          service_account: ${{ inputs.wif_sa }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Get Service and Repository Name
        id: get-service-repo
        working-directory: .
        run: |
          SERVICE_NAME=$(jq -r '.name' package.json)
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          echo "service_name=${SERVICE_NAME}" >> $GITHUB_ENV
          echo "repository_name=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tf-plan
          path: .infrastructure

      - name: Create terraform.tfvars file
        id: create-tfvars
        working-directory: .infrastructure
        run: |
          cat <<EOF > terraform.tfvars
          repository_name      = "${{ env.repository_name }}"
          project_id           = "${{ inputs.gcp_project_id }}"
          project_number       = "${{ inputs.gcp_project_number }}"
          region               = "${{ inputs.gcp_region }}"
          EOF
          terraform fmt terraform.tfvars

      - name: Create backend.tf file
        id: create-backend
        working-directory: .infrastructure
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "gcs" {
              bucket = "${{ inputs.terraform_state_bucket}}"
              prefix = "${{ env.service_name}}"
            }
          }
          EOF
          terraform fmt backend.tf

      - name: Terraform Init
        id: terraform-init
        working-directory: .infrastructure
        run: terraform init

      - name: Terraform Apply
        working-directory: .infrastructure
        run: |
          terraform apply tf.plan
          terraform output -json > output.json

      - name: Parse Terraform Output
        id: parse_output
        shell: bash
        working-directory: .infrastructure
        run: |
          if [ -f output.json ]; then
            OUTPUT_JSON=$(cat output.json | jq -c .)
            echo "output_json=${OUTPUT_JSON}" >> $GITHUB_OUTPUT
          else
            echo "output_json={}" >> $GITHUB_OUTPUT
          fi
