name: Terraform Apply

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      gcp_region:
        required: true
        type: string
      gcp_project_number:
        required: true
        type: string
      terraform_state_bucket:
        required: true
        type: string
      service_name:
        required: true
        type: string
      wif_provider:
        required: true
        type: string
      wif_sa:
        required: true
        type: string
    outputs:
      terraform_output:
        description: "Results from terraform apply in JSON format"
        value: ${{ jobs.apply.outputs.terraform_output }}


jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    outputs:
      terraform_output: ${{ steps.parse_output.outputs.output_json }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ inputs.gcp_project_id }}
          workload_identity_provider: ${{ inputs.wif_provider }}
          service_account: ${{ inputs.wif_sa }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tf-plan
          path: .infrastructure

      - name: Create terraform.tfvars file
        id: create-tfvars
        working-directory: .infrastructure
        run: |
          cat <<EOF > terraform.tfvars
          project_id           = "${{ inputs.gcp_project_id }}"
          project_number       = "${{ inputs.gcp_project_number }}"
          region               = "${{ inputs.gcp_region }}"
          EOF
          terraform fmt terraform.tfvars

      - name: Create backend.tf file
        id: create-backend
        working-directory: .infrastructure
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "gcs" {
              bucket = "${{ inputs.terraform_state_bucket}}"
              prefix = "${{ inputs.service_name}}"
            }
          }
          EOF
          terraform fmt backend.tf

      - name: Terraform Init
        id: terraform-init
        working-directory: .infrastructure
        run: terraform init

      - name: Terraform Apply
        working-directory: .infrastructure
        run: |
          terraform apply tf.plan
          terraform output -json > output.json

      - name: Parse Terraform Output
        id: parse_output # Step ID must match the mapping above
        shell: bash
        working-directory: .infrastructure
        run: |
          # (your script - consider adding jq install if needed: sudo apt-get update && sudo apt-get install -y jq)
          if [ -f output.json ]; then
            if jq -e . output.json > /dev/null; then # Validate JSON
                OUTPUT_JSON=$(cat output.json | jq -c .)
                echo "Parsed JSON: ${OUTPUT_JSON}" # Add logging
                echo "output_json=${OUTPUT_JSON}" >> $GITHUB_OUTPUT
            else
                echo "Error: output.json is not valid JSON."
                echo "output_json={}" >> $GITHUB_OUTPUT
            fi
          else
            echo "Warning: output.json not found."
            echo "output_json={}" >> $GITHUB_OUTPUT
          fi
