name: Terraform Workflow

on:
  push:
    branches:
      - main
    paths:
      - .infrastructure/*
      - .github/workflows/terraform.yml
      - .github/workflows/shared-terraform-*.yml
  pull_request:
    branches:
      - main
    paths:
      - .infrastructure/*
      - .github/workflows/terraform.yml
      - .github/workflows/shared-terraform-*.yml

jobs:
  plan:
    uses: ./.github/workflows/shared-terraform-plan.yml
    secrets: inherit
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_region: ${{ vars.GCP_REGION }}
      wif_provider: ${{ vars.WIF_PROVIDER }}
      wif_sa: ${{ vars.WIF_SA }}

  apply:
    needs: plan
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/shared-terraform-apply.yml
    secrets: inherit
    with:
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
      gcp_region: ${{ vars.GCP_REGION }}
      wif_provider: ${{ vars.WIF_PROVIDER }}
      wif_sa: ${{ vars.WIF_SA }}